apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 5000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /isAlive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  env:
    - name: APPLICATION_NAME
      value: {{application_name}}
    - name: CERT_PATH
      value: {{cert_path}}
    - name: VKS_SECRET_DEST_PATH
      value: {{secrets_path}}
    - name: POSTGRES_VAULT_PATH
      value: {{postgres_vault_path}}
    - name: VKS_VAULT_ADDR
      value: {{vks_vault_addr}}
    - name: VKS_AUTH_PATH
      value: {{vks_auth_path}}
    - name: VKS_KV_PATH
      value: {{vks_kv_path}}
    - name: K8S_SERVICEACCOUNT_PATH
      value: {{k8s_serviceaccount_path}}
  ingresses:
    - {{ingress}}
  leaderElection: false
  prometheus:
    enabled: true
    path: /
  istio:
    enabled: false
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
